Repository YAPP-Github/26th-App-Team-2-iOS, pull requests merged in 2025-08, with the labels that each got.

#57 Feat/#55 내정보
  DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  DependencyPlugin/ProjectDescriptionHelpers/Project+Environment.swift
  Projects/Core/LocalStorage/Interface/Sources/StorageProtocol/TokenStorageProtocol.swift
  Projects/Core/LocalStorage/Interface/Sources/StorageProtocol/UserStorageProtocol.swift
  Projects/Core/LocalStorage/Sources/KeyChainTokenStorage.swift
  Projects/Core/Network/Interface/Sources/APIRouter/BrakeRouter/AuthEndPoint.swift
  Projects/Core/Network/Interface/Sources/DTO/BrakeDTO/BrakeAuthDTO/Request/AuthLogoutRequest.swift
  Projects/Domain/OAuth/Interface/Sources/Service/OAuthLogoutServiceProtocol.swift
  Projects/Domain/OAuth/Interface/Sources/Service/OAuthServiceProtocol.swift
  Projects/Domain/OAuth/Interface/Sources/UseCase/OAuthLogoutUseCaseProtocol.swift
  Projects/Domain/OAuth/Sources/Service/OAuthLogInService.swift
  Projects/Domain/OAuth/Sources/Service/OAuthLogoutService.swift
  Projects/Domain/OAuth/Sources/Service/OAuthLogoutUseCase.swift
  Projects/Domain/User/Interface/Sources/Service/UserProfileProtocol.swift
  Projects/Domain/User/Interface/Sources/UseCase/DeleteUserUseCaseProtocol.swift
  Projects/Domain/User/Interface/Sources/UseCase/FetchUserNicknameUseCaseProtocol.swift
  Projects/Domain/User/Sources/DeleteUserUseCase.swift
  Projects/Domain/User/Sources/FetchUserNicknameUseCase.swift
  Projects/Domain/User/Sources/UserProfileService.swift
  Projects/Feature/AppGroupFeature/Interface/Sources/View/UpsertAppGroupView/ViewComponents/UpsertAppGroupNavigationView.swift
  Projects/Feature/MyInfo/Example/Sources/MyInfoExampleApp.swift
  Projects/Feature/MyInfo/Interface/Sources/DIContainer.swift
  Projects/Feature/MyInfo/Interface/Sources/Models/AccountSection.swift
  Projects/Feature/MyInfo/Interface/Sources/Models/SettingSection.swift
  Projects/Feature/MyInfo/Interface/Sources/MyInfoSettingView.swift
  Projects/Feature/MyInfo/Interface/Sources/ViewModels/MyInfoSettingViewModel.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/AccountSectionView.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/EditProfileView.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/FeedbackSectionView.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/LegalSectionView.swift
  Projects/Feature/MyInfo/Project.swift
  Projects/Feature/MyInfo/Sources/Source.swift
  Projects/Feature/MyInfo/Testing/Sources/MyInfoTesting.swift
  Projects/Feature/MyInfo/Tests/Sources/MyInfoTest.swift
  Projects/Feature/Onboarding/Interface/Sources/DIContainer.swift
  Projects/Feature/Onboarding/Interface/Sources/View/Login/LoginView.swift
  Projects/Feature/Onboarding/Interface/Sources/View/Onboarding/OnboardingInfoView.swift
  Projects/Feature/Onboarding/Interface/Sources/View/Onboarding/ScreenTimeAuthView.swift
  Projects/Feature/Onboarding/Interface/Sources/View/Onboarding/SetNickNameView.swift
  Projects/Feature/Onboarding/Interface/Sources/View/Onboarding/UserNotificationAuthView.swift
  Projects/Feature/Onboarding/Interface/Sources/ViewModel/LogInViewModel.swift
  Projects/Feature/Project.swift
  Projects/Feature/Sources/FeatureExport.swift
  Projects/Shared/DesignSystem/Example/Sources/BrakeNavigationView_ex.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icons/icon-profile.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icons/icon-profile.imageset/icon-profile.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icons/icon-profile.imageset/icon-profile@2x.png
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icons/icon-profile.imageset/icon-profile@3x.png
  Projects/Shared/DesignSystem/Sources/Extensions/ViewExtension.swift
  Projects/Shared/DesignSystem/Sources/Resourses/Colors.swift
  Projects/Shared/DesignSystem/Sources/Resourses/Fonts.swift
  Projects/Shared/DesignSystem/Sources/Resourses/Images/Images.swift
  Projects/Shared/DesignSystem/Sources/Views/Alert/BrakeAlertTwoButtonView.swift
  Projects/Shared/DesignSystem/Sources/Views/Alert/BrakeAlertView.swift
  Projects/Shared/DesignSystem/Sources/Views/Alert/BrakeIconAlert.swift
  Projects/Shared/DesignSystem/Sources/Views/BrakeNavigationView.swift
  Projects/Shared/DesignSystem/Sources/Views/Modifier/BrakePopUpModifier.swift
  Projects/Shared/Util/Sources/Models/ExternalLink.swift
Labels: feature

#66 Fix/#65-계정 관련 API 기능 개선
  History/#65-계정관련API기능개선.md
  Projects/App/Sources/DIContainer/CoreDIContainer.swift
  Projects/App/Sources/DIContainer/ServiceDIContainer.swift
  Projects/App/Sources/Views/MainAppView.swift
  Projects/App/Sources/Views/MainTabView.swift
  Projects/Core/LocalStorage/Interface/Sources/Errors/AppGroupStorageError.swift
  Projects/Core/LocalStorage/Interface/Sources/StorageProtocol/AppGroupStorageProtocol.swift
  Projects/Core/LocalStorage/Interface/Sources/StorageProtocol/ResetLocalStorageProtocol.swift
  Projects/Core/LocalStorage/Interface/Sources/StorageProtocol/UserStorageProtocol.swift
  Projects/Core/LocalStorage/Sources/AppGroupStorage.swift
  Projects/Core/LocalStorage/Sources/UserDefaultsUserStorage.swift
  Projects/Core/Network/Interface/Sources/APIRouter/BrakeRouter/AuthEndPoint.swift
  Projects/Core/Network/Interface/Sources/Networkable/HTTPResponseProtocol.swift
  Projects/Core/Network/Sources/NetworkProvider.swift
  Projects/Domain/OAuth/Sources/Service/OAuthLogoutService.swift
  Projects/Domain/OAuth/Sources/Service/OAuthLogoutUseCase.swift
  Projects/Domain/Shared/Interface/Sources/Service/AppGroupService.swift
  Projects/Domain/User/Interface/Sources/Service/UserProfileProtocol.swift
  Projects/Domain/User/Sources/UserProfileService.swift
  Projects/Feature/MyInfo/Interface/Sources/DIContainer.swift
  Projects/Feature/MyInfo/Interface/Sources/MyInfoSettingView.swift
  Projects/Feature/MyInfo/Interface/Sources/ViewModels/MyInfoSettingViewModel.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/AccountSectionView.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/EditProfileView.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/FeedbackSectionView.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/LegalSectionView.swift
  Projects/Feature/MyInfo/Interface/Sources/Views/ViewComponents/MyInfoMainSettingCell.swift
  Projects/Feature/Onboarding/Interface/Sources/DIContainer.swift
  Projects/Feature/Onboarding/Interface/Sources/ViewModel/StartUpViewModel.swift
  Projects/Shared/DesignSystem/Sources/Models/TabItemType.swift
  Projects/Shared/DesignSystem/Sources/Views/BrakeTabBarView.swift
Labels: refactor, fix

#70 Refactor/#67-휴게시간 설정 스크롤 범위 변경
  Projects/Feature/AppGroupFeature/Interface/Sources/View/AppBrakeTimeSettingView.swift
Labels: refactor

#73 Feat/#71 앱 모듈 privacy 파일, Extension Privacy 파일 추가
  Projects/App/Extensions/DeviceActivityMonitorExtension/PrivacyInfo.xcprivacy
  Projects/App/Extensions/ShieldActionConfigurationExtension/PrivacyInfo.xcprivacy
  Projects/App/Extensions/ShieldConfigurationExtension/PrivacyInfo.xcprivacy
  Projects/App/Resources/PrivacyInfo.xcprivacy
  Tuist/ProjectDescriptionHelpers/Target+Templates/Target+App.swift
Labels: feature

#76 Refactor/#75-brake status manage
  History/#75-breake-앱모듈-에러처리.md
  Projects/App/Extensions/ShieldConfigurationExtension/Sources/ShieldConfigurationExtension.swift
  Projects/App/Sources/Views/MainTapView/MainTabView.swift
  Projects/Core/AppScreenTime/Sources/Managers/BlockScheduleManager.swift
  Projects/Domain/ScreenTimeManagement/Interface/Sources/BreakTime/EndBreakTimeUseCaseProtocol.swift
  Projects/Domain/ScreenTimeManagement/Interface/Sources/BreakTime/SnoozeBreakTimeUseCaseProtocol.swift
  Projects/Domain/ScreenTimeManagement/Sources/BreakTime/SnoozeBreakTimeUseCase.swift
  Projects/Feature/AppGroupFeature/Interface/Sources/View/AppGroupMainView/AppGroupMainView.swift
  Projects/Feature/AppGroupFeature/Interface/Sources/View/AppGroupMainView/ViewComponents/AppGroupMainGroupListCell.swift
  Projects/Feature/AppGroupFeature/Interface/Sources/View/AppGroupMainView/ViewComponents/AppGroupMainGroupListView.swift
  Projects/Feature/AppGroupFeature/Interface/Sources/ViewModel/AppBrakeTimeSettingViewModel.swift
  Projects/Feature/AppGroupFeature/Interface/Sources/ViewModel/AppGroupMainViewModel.swift
  Projects/Feature/AppGroupFeature/Interface/Sources/ViewModel/UpsertAppGroupViewModel.swift
  Projects/Shared/DesignSystem/Example/Sources/BrakePopUpView_ex.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates/Target+App.swift
Labels: bug, refactor, fix
